# Generated by Django 3.0.3 on 2020-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblogs', '0003_auto_20200608_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Sports', max_length=255),
        ),
    ]
