# Generated by Django 3.0.3 on 2020-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblogs', '0006_auto_20200610_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='Click to read more'),
        ),
    ]
