# Generated by Django 3.0.3 on 2020-06-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theblogs', '0009_post_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
