# Generated by Django 3.0.3 on 2020-06-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theblogs', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
